[package]
name = "gdk-pixbuf"
license = "MIT"
homepage = "http://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
keywords = ["gdk-pixbuf", "gtk-rs", "gnome"]
readme = "README.md"
documentation = "http://gtk-rs.org/docs/gdk_pixbuf/"
version = "0.7.0"
description = "Rust bindings for the GdkPixbuf library"
repository = "https://github.com/gtk-rs/gdk-pixbuf"
build = "build.rs"
exclude = [
    "gir-files/*",
]

[badges]
appveyor = { repository = "GuillaumeGomez/gdk-pixbuf", service = "github" }
travis-ci = { repository = "gtk-rs/gdk-pixbuf" }

[lib]
name = "gdk_pixbuf"

[features]
v2_32 = ["gdk-pixbuf-sys/v2_32"]
v2_36 = ["v2_32", "gdk-pixbuf-sys/v2_36"]
v2_36_8 = ["v2_36", "gdk-pixbuf-sys/v2_36_8"]
dox = ["glib/dox", "gdk-pixbuf-sys/dox"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs"]
futures = ["futures-preview", "fragile", "glib/futures", "gio/futures"]

[build-dependencies.gtk-rs-lgpl-docs]
version = "0.1.3"
optional = true

[dependencies]
libc = "0.2"
fragile = { version = "0.3", optional = true }
futures-preview = { version = "0.3.0-alpha", optional = true }
# gdk-pixbuf-sys = "0.9.0"
gdk-pixbuf-sys = { git = "https://github.com/cthorner/sys", branch = "crate-custom", version = "0.9.0" }
# glib = "0.8.0"
glib = { git = "https://github.com/cthorner/glib", branch = "0.8.0-custom", version = "0.8.0" }
# glib-sys = "0.9.0"
glib-sys = { git = "https://github.com/cthorner/sys", branch = "crate-custom", version = "0.9.0" }
# gobject-sys = "0.9.0"
gobject-sys = { git = "https://github.com/cthorner/sys", branch = "crate-custom", version = "0.9.0" }
# gio-sys = "0.9.0"
gio-sys = { git = "https://github.com/cthorner/sys", branch = "crate-custom", version = "0.9.0" }
# gio = "0.7.0"
gio = { git = "https://github.com/cthorner/gio", branch="0.7-custom", version="0.7.0", features=["v2_48"] } # per configure.ac

[dev-dependencies]
gir-format-check = "^0.1"
